version: "3.9"
services:
  bot:
    build: .
    ports:
      - "3000:3001"
    environment:
      - PORT=3001
      - SLACK_SIGNING_SECRET
      - SLACK_BOT_TOKEN
      - TWILIO_AUTH_TOKEN
      - TWILIO_ACCOUNT_SID
      - TASKROUTER_WORKSPACE_SID

